### ISSUE TITLE
How to use flink's remote execution environment

### ISSUE THREAD

**Issue by vsimko** [biggis-project/biggis-infrastructure#10]
I started the biggis docker architecture using `docker-compose up`. Here is a list of running apps:

``` sh
$ docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                              NAMES
2834ff131651        biggis/flink:1.0.3         "/usr/local/bin/entry"   23 minutes ago      Up 23 minutes                                          biggispipeline_taskmanager_1
30eb846d69df        biggis/collector:0.9.0.0   "/usr/local/bin/entry"   23 minutes ago      Up 23 minutes       7203/tcp, 9092/tcp                 biggispipeline_collector_1
421fb38c562d        biggis/flink:1.0.3         "/usr/local/bin/entry"   23 minutes ago      Up 23 minutes       0.0.0.0:8081->8081/tcp             biggispipeline_jobmanager_1
900a33c5735c        biggis/kafka:0.9.0.0       "/usr/local/bin/entry"   23 minutes ago      Up 23 minutes       7203/tcp, 0.0.0.0:9092->9092/tcp   biggispipeline_kafka_1
9d7de7dfb2d1        biggis/mysql:10.1          "mysqld --skip-grant-"   23 minutes ago      Up 23 minutes       0.0.0.0:3306->3306/tcp             biggispipeline_db_1
64ebb0876f7b        biggis/zookeeper:3.4.6     "/usr/local/bin/entry"   23 minutes ago      Up 23 minutes       2181/tcp, 2888/tcp, 3888/tcp       biggispipeline_zookeeper_1
```

I can easily connect to flink web console at [http://localhost:8081](http://localhost:8081)
Now, I would like to use Eclipse to develop some flink jobs and to run them inside the docker container.

``` xtend
// this will use local environment and not the remote environement
// from biggispipeline_jobmanager_1
val env = ExecutionEnvironment.executionEnvironment
```

Then, I tried to use `createRemoteEnvironment` function, but I don't know which port to use (8081 does not work)

``` xtend
val env = ExecutionEnvironment.createRemoteEnvironment("localhost", ????)
```

**Comment by vsimko** [comment]
looking into https://ci.apache.org/projects/flink/flink-docs-release-0.8/config.html
I think, the needed port is `jobmanager.rpc.port` (DEFAULT: 6123).

**Comment by wipatrick** [comment]
the default port on the jobmanager side is indeed 6123. We need to expose that port in the `docker-compose.yml` in order to connect from the "outside" world, in that case your machine.

To be honest, my workflow was rather to use the local environment for debugging and coding and once done, package a jar and submit this artifact to the flink cluster. Haven't tried to use the remote execution setup.

see:

https://ci.apache.org/projects/flink/flink-docs-master/api/java/org/apache/flink/api/java/RemoteEnvironment.html

**Comment by wipatrick** [comment]
## **Docker Host=Host (Linux)**

I guess if you're running native Linux as Docker Host the following changes will be reduced drastically since the docker containers ip address is known to your machine via `docker0` bridge. Thus, specifying the jobmanager's container ip address in your code might be sufficient. You must `mvn clean package` your user-defined code and provide the remote environment with the _path/to/jar(s)_.

``` scala
val env = ExecutionEnvironment.createRemoteEnvironment("<jm_container_ip>", <jm_port>, "<path/to/jar(s)>")
```

Could you please confirm if it's working @vsimko?

## **Docker Host=VM (Linux)**

I tested the following setup:
**Mac OSx** <--> **VM** <--> **Container** (Flinks jobmanager)

From within your IDE you'll need to specify the following:

``` scala
val env = ExecutionEnvironment.createRemoteEnvironment("<jm_ip>/<jm_hostname>", <jm_port>, "<path/to/jar(s)>")
```

The _jarfiles_ of your project are needed since they contain user-defined code. So before deploying your code to the "remote" container you will need to run

``` maven
mvn clean package
```

and specify the _path/to/jar(s)_.

Since the IP addresses of containers inside my VM are not accessible from my machine, I will need to start Flinks jobmanager in 

``` yaml
  jobmanager:
    image: biggis/flink:1.0.3
    restart: always
    hostname: jobmanager
    depends_on:
      - db
      - kafka
    network_mode: "host"
    # ports:
    #   - "8081:8081"
    #   - "6123:6123"
    command: docker-entrypoint.sh jobmanager
    environment:
      USER_ID: ${USER_ID}
      USER_NAME: flink
    volumes:
      - flink-conf:/opt/flink/conf
```

The important part is `network_mode: host`. This will not containerized the network of Flinks jobmanager and uses the Docker Hosts network stack. Please note, that it is then not neccessary to do a port mapping since it will use the Docker Hosts ports as specified by Flinks `flink-conf.yaml`.

The way the `biggis/flink` image is build it will set the `jobmanager.rpc.address` inside `flink-conf.yaml` on container startup using

``` sh
sed -i -e "s/jobmanager.rpc.address: localhost/jobmanager.rpc.address: `hostname -i`/g" $FLINK_HOME/conf/flink-conf.yaml
```

which will lead to setting it to either container ip (standard setup, network_mode: host commented) or to 127.0.0.1 (network_mode: host). By manually editing this entry to my VM's ip address (192.168.99.100) `jobmanager.rpc.address: 192.168.99.100` and restarting Flinks jobmanager and taskmanager, I am then able to execute code from within my IDE inside the Docker containers.

``` sh
➜  biggis-pipeline git:(master) ✗ dm ssh ProxBoxDev
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|

  WARNING: this is a test.docker.com build, not a release.

Boot2Docker version 1.11.1-rc1, build HEAD : 903a352 - Tue Apr 26 14:18:06 UTC 2016
Docker version 1.11.1-rc1, build c90c70c
docker@ProxBoxDev:~$ sudo su
root@ProxBoxDev:/mnt/sda1/var/lib/docker/volumes/biggispipeline_flink-conf/_data# vi flink-conf.yaml
root@ProxBoxDev:/mnt/sda1/var/lib/docker/volumes/biggispipeline_flink-conf/_data# exit
docker@ProxBoxDev:~$ exit
➜  biggis-pipeline git:(master) ✗ docker-compose restart jobmanager taskmanager
Restarting biggispipeline_taskmanager_1 ... done
Restarting biggispipeline_jobmanager_1 ... done
```

Simple scala wordcount example:

``` scala
import org.apache.flink.api.scala._

/**
 * Implements the "WordCount" program that computes a simple word occurrence histogram
 * over some sample data
 *
 * This example shows how to:
 *
 *   - write a simple Flink program.
 *   - use Tuple data types.
 *   - write and use user-defined functions.
 */
object WordCount {
  def main(args: Array[String]) {

    // set up the execution environment
    /*val env = ExecutionEnvironment.getExecutionEnvironment*/
    val env = ExecutionEnvironment.createRemoteEnvironment("192.168.99.100", 6123, "target/flink-scala-project-0.1.jar");

    // get input data
    val text = env.fromElements("To be, or not to be,--that is the question:--",
      "Whether 'tis nobler in the mind to suffer", "The slings and arrows of outrageous fortune",
      "Or to take arms against a sea of troubles,")

    val counts = text.flatMap { _.toLowerCase.split("\\W+") }
      .map { (_, 1) }
      .groupBy(0)
      .sum(1)

    // execute and print result
    counts.print()

  }
}
```

And the corresponding stdout from within IntelliJ:

``` sh
10:02:41,772 INFO  org.apache.flink.api.java.ExecutionEnvironment                - The job has 0 registered types and 0 default Kryo serializers
10:02:41,781 INFO  org.apache.flink.client.program.Client                        - Starting client actor system
10:02:41,782 INFO  org.apache.flink.runtime.client.JobClient                     - Starting JobClient actor system
10:02:42,241 INFO  akka.event.slf4j.Slf4jLogger                                  - Slf4jLogger started
10:02:42,294 INFO  Remoting                                                      - Starting remoting
10:02:42,448 INFO  Remoting                                                      - Remoting started; listening on addresses :[akka.tcp://flink@127.0.0.1:60782]
10:02:42,463 INFO  org.apache.flink.runtime.client.JobClient                     - Started JobClient actor system at 127.0.0.1:60782
10:02:42,684 INFO  org.apache.flink.runtime.client.JobClientActor                - Disconnect from JobManager null.
10:02:42,693 INFO  org.apache.flink.runtime.client.JobClientActor                - Received job Flink Java Job at Fri Jul 15 10:02:11 CEST 2016 (8302975b5764c1e00cb2a936c4dc95c6).
10:02:42,693 INFO  org.apache.flink.runtime.client.JobClientActor                - Could not submit job Flink Java Job at Fri Jul 15 10:02:11 CEST 2016 (8302975b5764c1e00cb2a936c4dc95c6), because there is no connection to a JobManager.
10:02:42,944 INFO  org.apache.flink.runtime.client.JobClientActor                - Connect to JobManager Actor[akka.tcp://flink@192.168.99.100:6123/user/jobmanager#2054169097].
10:02:42,945 INFO  org.apache.flink.runtime.client.JobClientActor                - Connected to new JobManager akka.tcp://flink@192.168.99.100:6123/user/jobmanager.
10:02:42,949 INFO  org.apache.flink.runtime.client.JobClientActor                - Sending message to JobManager akka.tcp://flink@192.168.99.100:6123/user/jobmanager to submit job Flink Java Job at Fri Jul 15 10:02:11 CEST 2016 (8302975b5764c1e00cb2a936c4dc95c6) and wait for progress
10:02:42,952 INFO  org.apache.flink.runtime.client.JobClientActor                - Upload jar files to job manager akka.tcp://flink@192.168.99.100:6123/user/jobmanager.
10:02:43,290 INFO  org.apache.flink.runtime.client.JobClientActor                - Submit job to the job manager akka.tcp://flink@192.168.99.100:6123/user/jobmanager.
10:02:43,349 INFO  org.apache.flink.runtime.client.JobClientActor                - Job was successfully submitted to the JobManager akka.tcp://flink@192.168.99.100:6123/user/jobmanager.
10:02:43,352 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  Job execution switched to status RUNNING.
07/15/2016 10:02:43 Job execution switched to status RUNNING.
10:02:43,358 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  CHAIN DataSource (at org.apache.flink.api.scala.ExecutionEnvironment.fromElements(ExecutionEnvironment.scala:567) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:45)) -> Map (Map at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:46)) -> Combine(SUM(1))(1/1) switched to SCHEDULED 
07/15/2016 10:02:43 CHAIN DataSource (at org.apache.flink.api.scala.ExecutionEnvironment.fromElements(ExecutionEnvironment.scala:567) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:45)) -> Map (Map at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:46)) -> Combine(SUM(1))(1/1) switched to SCHEDULED 
10:02:43,358 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  CHAIN DataSource (at org.apache.flink.api.scala.ExecutionEnvironment.fromElements(ExecutionEnvironment.scala:567) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:45)) -> Map (Map at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:46)) -> Combine(SUM(1))(1/1) switched to DEPLOYING 
07/15/2016 10:02:43 CHAIN DataSource (at org.apache.flink.api.scala.ExecutionEnvironment.fromElements(ExecutionEnvironment.scala:567) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:45)) -> Map (Map at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:46)) -> Combine(SUM(1))(1/1) switched to DEPLOYING 
10:02:43,396 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  CHAIN DataSource (at org.apache.flink.api.scala.ExecutionEnvironment.fromElements(ExecutionEnvironment.scala:567) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:45)) -> Map (Map at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:46)) -> Combine(SUM(1))(1/1) switched to RUNNING 
07/15/2016 10:02:43 CHAIN DataSource (at org.apache.flink.api.scala.ExecutionEnvironment.fromElements(ExecutionEnvironment.scala:567) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:45)) -> Map (Map at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:46)) -> Combine(SUM(1))(1/1) switched to RUNNING 
10:02:43,565 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  Reduce (SUM(1))(1/1) switched to SCHEDULED 
07/15/2016 10:02:43 Reduce (SUM(1))(1/1) switched to SCHEDULED 
10:02:43,568 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  Reduce (SUM(1))(1/1) switched to DEPLOYING 
07/15/2016 10:02:43 Reduce (SUM(1))(1/1) switched to DEPLOYING 
10:02:43,600 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  CHAIN DataSource (at org.apache.flink.api.scala.ExecutionEnvironment.fromElements(ExecutionEnvironment.scala:567) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:45)) -> Map (Map at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:46)) -> Combine(SUM(1))(1/1) switched to FINISHED 
07/15/2016 10:02:43 CHAIN DataSource (at org.apache.flink.api.scala.ExecutionEnvironment.fromElements(ExecutionEnvironment.scala:567) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:45)) -> Map (Map at org.apache.flink.quickstart.WordCount$.main(WordCount.scala:46)) -> Combine(SUM(1))(1/1) switched to FINISHED 
10:02:43,612 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  Reduce (SUM(1))(1/1) switched to RUNNING 
07/15/2016 10:02:43 Reduce (SUM(1))(1/1) switched to RUNNING 
10:02:43,812 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  DataSink (collect())(1/1) switched to SCHEDULED 
07/15/2016 10:02:43 DataSink (collect())(1/1) switched to SCHEDULED 
10:02:43,812 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  DataSink (collect())(1/1) switched to DEPLOYING 
07/15/2016 10:02:43 DataSink (collect())(1/1) switched to DEPLOYING 
10:02:43,824 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  Reduce (SUM(1))(1/1) switched to FINISHED 
07/15/2016 10:02:43 Reduce (SUM(1))(1/1) switched to FINISHED 
10:02:43,846 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  DataSink (collect())(1/1) switched to RUNNING 
07/15/2016 10:02:43 DataSink (collect())(1/1) switched to RUNNING 
10:02:43,883 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  DataSink (collect())(1/1) switched to FINISHED 
07/15/2016 10:02:43 DataSink (collect())(1/1) switched to FINISHED 
10:02:43,883 INFO  org.apache.flink.runtime.client.JobClientActor                - 07/15/2016 10:02:43  Job execution switched to status FINISHED.
07/15/2016 10:02:43 Job execution switched to status FINISHED.
10:02:43,892 INFO  org.apache.flink.runtime.client.JobClientActor                - Terminate JobClientActor.
10:02:43,892 INFO  org.apache.flink.runtime.client.JobClientActor                - Disconnect from JobManager Actor[akka.tcp://flink@192.168.99.100:6123/user/jobmanager#2054169097].
10:02:43,894 INFO  org.apache.flink.runtime.client.JobClient                     - Job execution complete
10:02:43,920 INFO  akka.remote.RemoteActorRefProvider$RemotingTerminator         - Shutting down remote daemon.
10:02:43,923 INFO  akka.remote.RemoteActorRefProvider$RemotingTerminator         - Remote daemon shut down; proceeding with flushing remote transports.
10:02:43,974 INFO  akka.remote.RemoteActorRefProvider$RemotingTerminator         - Remoting shut down.
(a,1)
(against,1)
(and,1)
(arms,1)
(arrows,1)
(be,2)
(fortune,1)
(in,1)
(is,1)
(mind,1)
(nobler,1)
(not,1)
(of,2)
(or,2)
(outrageous,1)
(question,1)
(sea,1)
(slings,1)
(suffer,1)
(take,1)
(that,1)
(the,3)
(tis,1)
(to,4)
(troubles,1)
(whether,1)

Process finished with exit code 0
```

**Comment by vsimko** [comment]
The option **Docker Host=Host (Linux)** works.
The only problem is that I need to run `mvn clean package` everytime I change the code.
I'll therefore use the local flink for development which is more convenient.

Here is a minimal example that works from Eclipse.

``` java
package de.biggis.flink;

import org.apache.flink.api.java.ExecutionEnvironment;

public class Testik {

    public static void main(String[] args) throws Exception {
        ExecutionEnvironment
        .createRemoteEnvironment("172.18.0.5", 6123, "target/biggis-tiledb-1.0-SNAPSHOT.jar")
        .fromElements(1, 2, 3, 4, 5, 6)
        .filter(x -> x > 3)
        .print();
    }

}
```

**Comment by wipatrick** [comment]
exactly. more convenient even fast for fast debugging, because you would have to upload the _jarfile_ every time.
